services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    container_name: robotos-jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc:/var/jenkins_home/casc
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc/jenkins.yaml
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}

volumes:
  jenkins_home:
