# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neodm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'neodm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bneodm.proto\x12\x05neodm\"\\\n\x0f\x44\x65\x63isionRequest\x12\x11\n\tnav_state\x18\x01 \x01(\t\x12\x13\n\x0b\x62\x61ttery_pct\x18\x02 \x01(\x02\x12\x0f\n\x07is_held\x18\x03 \x01(\x08\x12\x10\n\x08obstacle\x18\x04 \x01(\x08\"[\n\x10\x44\x65\x63isionResponse\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x13\n\x0btarget_goal\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0e\n\x06reason\x18\x04 \x01(\t\"\x0e\n\x0cStateRequest\"S\n\nNeoDMState\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x0f\n\x07loop_hz\x18\x03 \x01(\x02\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\x80\x01\n\x05NeoDM\x12>\n\x0bGetDecision\x12\x16.neodm.DecisionRequest\x1a\x17.neodm.DecisionResponse\x12\x37\n\x0bStreamState\x12\x13.neodm.StateRequest\x1a\x11.neodm.NeoDMState0\x01\x42?Z=github.com/mannsub/robotos/middleware/services/neodm/proto/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neodm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z=github.com/mannsub/robotos/middleware/services/neodm/proto/go'
  _globals['_DECISIONREQUEST']._serialized_start=22
  _globals['_DECISIONREQUEST']._serialized_end=114
  _globals['_DECISIONRESPONSE']._serialized_start=116
  _globals['_DECISIONRESPONSE']._serialized_end=207
  _globals['_STATEREQUEST']._serialized_start=209
  _globals['_STATEREQUEST']._serialized_end=223
  _globals['_NEODMSTATE']._serialized_start=225
  _globals['_NEODMSTATE']._serialized_end=308
  _globals['_NEODM']._serialized_start=311
  _globals['_NEODM']._serialized_end=439
# @@protoc_insertion_point(module_scope)
