# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import neodm_pb2 as neodm__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in neodm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NeoDMStub(object):
    """NeoDM - Neo Decision Maker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDecision = channel.unary_unary(
                '/neodm.NeoDM/GetDecision',
                request_serializer=neodm__pb2.DecisionRequest.SerializeToString,
                response_deserializer=neodm__pb2.DecisionResponse.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/neodm.NeoDM/StreamState',
                request_serializer=neodm__pb2.StateRequest.SerializeToString,
                response_deserializer=neodm__pb2.NeoDMState.FromString,
                _registered_method=True)


class NeoDMServicer(object):
    """NeoDM - Neo Decision Maker
    """

    def GetDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NeoDMServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDecision,
                    request_deserializer=neodm__pb2.DecisionRequest.FromString,
                    response_serializer=neodm__pb2.DecisionResponse.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=neodm__pb2.StateRequest.FromString,
                    response_serializer=neodm__pb2.NeoDMState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neodm.NeoDM', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neodm.NeoDM', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NeoDM(object):
    """NeoDM - Neo Decision Maker
    """

    @staticmethod
    def GetDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neodm.NeoDM/GetDecision',
            neodm__pb2.DecisionRequest.SerializeToString,
            neodm__pb2.DecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/neodm.NeoDM/StreamState',
            neodm__pb2.StateRequest.SerializeToString,
            neodm__pb2.NeoDMState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
