services:
  redis:
    image: redis:7-alpine
    platform: linux/arm64
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --save "" --appendonly no

  neodm:
    build:
      context: ..
      dockerfile: docker/neodm.Dockerfile
    platform: linux/arm64
    ports:
      - "50051:50051"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped

  robotos:
    build:
      context: ..
      dockerfile: docker/go.Dockerfile
    platform: linux/arm64
    depends_on:
      - neodm
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    restart: unless-stopped
