// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: neodm.proto

package neodmpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NeoDM_GetDecision_FullMethodName = "/neodm.NeoDM/GetDecision"
	NeoDM_StreamState_FullMethodName = "/neodm.NeoDM/StreamState"
)

// NeoDMClient is the client API for NeoDM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NeoDM - Neo Decision Maker
type NeoDMClient interface {
	GetDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
	StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NeoDMState], error)
}

type neoDMClient struct {
	cc grpc.ClientConnInterface
}

func NewNeoDMClient(cc grpc.ClientConnInterface) NeoDMClient {
	return &neoDMClient{cc}
}

func (c *neoDMClient) GetDecision(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, NeoDM_GetDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neoDMClient) StreamState(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NeoDMState], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NeoDM_ServiceDesc.Streams[0], NeoDM_StreamState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StateRequest, NeoDMState]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeoDM_StreamStateClient = grpc.ServerStreamingClient[NeoDMState]

// NeoDMServer is the server API for NeoDM service.
// All implementations must embed UnimplementedNeoDMServer
// for forward compatibility.
//
// NeoDM - Neo Decision Maker
type NeoDMServer interface {
	GetDecision(context.Context, *DecisionRequest) (*DecisionResponse, error)
	StreamState(*StateRequest, grpc.ServerStreamingServer[NeoDMState]) error
	mustEmbedUnimplementedNeoDMServer()
}

// UnimplementedNeoDMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNeoDMServer struct{}

func (UnimplementedNeoDMServer) GetDecision(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDecision not implemented")
}
func (UnimplementedNeoDMServer) StreamState(*StateRequest, grpc.ServerStreamingServer[NeoDMState]) error {
	return status.Error(codes.Unimplemented, "method StreamState not implemented")
}
func (UnimplementedNeoDMServer) mustEmbedUnimplementedNeoDMServer() {}
func (UnimplementedNeoDMServer) testEmbeddedByValue()               {}

// UnsafeNeoDMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NeoDMServer will
// result in compilation errors.
type UnsafeNeoDMServer interface {
	mustEmbedUnimplementedNeoDMServer()
}

func RegisterNeoDMServer(s grpc.ServiceRegistrar, srv NeoDMServer) {
	// If the following call panics, it indicates UnimplementedNeoDMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NeoDM_ServiceDesc, srv)
}

func _NeoDM_GetDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NeoDMServer).GetDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NeoDM_GetDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NeoDMServer).GetDecision(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NeoDM_StreamState_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NeoDMServer).StreamState(m, &grpc.GenericServerStream[StateRequest, NeoDMState]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NeoDM_StreamStateServer = grpc.ServerStreamingServer[NeoDMState]

// NeoDM_ServiceDesc is the grpc.ServiceDesc for NeoDM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NeoDM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "neodm.NeoDM",
	HandlerType: (*NeoDMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDecision",
			Handler:    _NeoDM_GetDecision_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamState",
			Handler:       _NeoDM_StreamState_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "neodm.proto",
}
