// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: neodm.proto

package neodmpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NavState      string                 `protobuf:"bytes,1,opt,name=nav_state,json=navState,proto3" json:"nav_state,omitempty"` // "IDLE" | "NAVIGATION" | "ARRIVED" | "FAILED"
	BatteryPct    float32                `protobuf:"fixed32,2,opt,name=battery_pct,json=batteryPct,proto3" json:"battery_pct,omitempty"`
	IsHeld        bool                   `protobuf:"varint,3,opt,name=is_held,json=isHeld,proto3" json:"is_held,omitempty"`
	Obstacle      bool                   `protobuf:"varint,4,opt,name=obstacle,proto3" json:"obstacle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_neodm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neodm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_neodm_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetNavState() string {
	if x != nil {
		return x.NavState
	}
	return ""
}

func (x *DecisionRequest) GetBatteryPct() float32 {
	if x != nil {
		return x.BatteryPct
	}
	return 0
}

func (x *DecisionRequest) GetIsHeld() bool {
	if x != nil {
		return x.IsHeld
	}
	return false
}

func (x *DecisionRequest) GetObstacle() bool {
	if x != nil {
		return x.Obstacle
	}
	return false
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "NAVIGATION" | "IDLE" | "STOP" | "DOCK"
	TargetGoal    string                 `protobuf:"bytes,2,opt,name=target_goal,json=targetGoal,proto3" json:"target_goal,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_neodm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_neodm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_neodm_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DecisionResponse) GetTargetGoal() string {
	if x != nil {
		return x.TargetGoal
	}
	return ""
}

func (x *DecisionResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *DecisionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_neodm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_neodm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_neodm_proto_rawDescGZIP(), []int{2}
}

type NeoDMState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emotion       string                 `protobuf:"bytes,1,opt,name=emotion,proto3" json:"emotion,omitempty"` // Phase 2: emotion model
	Decision      string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	LoopHz        float32                `protobuf:"fixed32,3,opt,name=loop_hz,json=loopHz,proto3" json:"loop_hz,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix mx
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeoDMState) Reset() {
	*x = NeoDMState{}
	mi := &file_neodm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeoDMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeoDMState) ProtoMessage() {}

func (x *NeoDMState) ProtoReflect() protoreflect.Message {
	mi := &file_neodm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeoDMState.ProtoReflect.Descriptor instead.
func (*NeoDMState) Descriptor() ([]byte, []int) {
	return file_neodm_proto_rawDescGZIP(), []int{3}
}

func (x *NeoDMState) GetEmotion() string {
	if x != nil {
		return x.Emotion
	}
	return ""
}

func (x *NeoDMState) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *NeoDMState) GetLoopHz() float32 {
	if x != nil {
		return x.LoopHz
	}
	return 0
}

func (x *NeoDMState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_neodm_proto protoreflect.FileDescriptor

const file_neodm_proto_rawDesc = "" +
	"\n" +
	"\vneodm.proto\x12\x05neodm\"\x84\x01\n" +
	"\x0fDecisionRequest\x12\x1b\n" +
	"\tnav_state\x18\x01 \x01(\tR\bnavState\x12\x1f\n" +
	"\vbattery_pct\x18\x02 \x01(\x02R\n" +
	"batteryPct\x12\x17\n" +
	"\ais_held\x18\x03 \x01(\bR\x06isHeld\x12\x1a\n" +
	"\bobstacle\x18\x04 \x01(\bR\bobstacle\"\x83\x01\n" +
	"\x10DecisionResponse\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_goal\x18\x02 \x01(\tR\n" +
	"targetGoal\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x0e\n" +
	"\fStateRequest\"y\n" +
	"\n" +
	"NeoDMState\x12\x18\n" +
	"\aemotion\x18\x01 \x01(\tR\aemotion\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12\x17\n" +
	"\aloop_hz\x18\x03 \x01(\x02R\x06loopHz\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x80\x01\n" +
	"\x05NeoDM\x12>\n" +
	"\vGetDecision\x12\x16.neodm.DecisionRequest\x1a\x17.neodm.DecisionResponse\x127\n" +
	"\vStreamState\x12\x13.neodm.StateRequest\x1a\x11.neodm.NeoDMState0\x01B$Z\"github.com/mannsub/robotos/neodmpbb\x06proto3"

var (
	file_neodm_proto_rawDescOnce sync.Once
	file_neodm_proto_rawDescData []byte
)

func file_neodm_proto_rawDescGZIP() []byte {
	file_neodm_proto_rawDescOnce.Do(func() {
		file_neodm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_neodm_proto_rawDesc), len(file_neodm_proto_rawDesc)))
	})
	return file_neodm_proto_rawDescData
}

var file_neodm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_neodm_proto_goTypes = []any{
	(*DecisionRequest)(nil),  // 0: neodm.DecisionRequest
	(*DecisionResponse)(nil), // 1: neodm.DecisionResponse
	(*StateRequest)(nil),     // 2: neodm.StateRequest
	(*NeoDMState)(nil),       // 3: neodm.NeoDMState
}
var file_neodm_proto_depIdxs = []int32{
	0, // 0: neodm.NeoDM.GetDecision:input_type -> neodm.DecisionRequest
	2, // 1: neodm.NeoDM.StreamState:input_type -> neodm.StateRequest
	1, // 2: neodm.NeoDM.GetDecision:output_type -> neodm.DecisionResponse
	3, // 3: neodm.NeoDM.StreamState:output_type -> neodm.NeoDMState
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_neodm_proto_init() }
func file_neodm_proto_init() {
	if File_neodm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_neodm_proto_rawDesc), len(file_neodm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_neodm_proto_goTypes,
		DependencyIndexes: file_neodm_proto_depIdxs,
		MessageInfos:      file_neodm_proto_msgTypes,
	}.Build()
	File_neodm_proto = out.File
	file_neodm_proto_goTypes = nil
	file_neodm_proto_depIdxs = nil
}
